#
# Extract package to github folder
#
# - Make sure to upload archive separately first.
# - Then run this script next.
#


image: macos


clone_depth: 50



environment:

  GIT_SCRIPT: SiennaSilver


  GIT_LOGIN:
    secure: qOA9yxm90ZYtTb+LWeLytw==




build_script:

  - ps: |

      if (${env:GIT_SCRIPT} -Eq $Null) {
        $env:GIT_SCRIPT = $env:APPVEYOR_REPO_COMMIT_AUTHOR
      }



      # git reset --hard HEAD~1



      ##################################



      try {
        iex ((New-Object System.Net.WebClient).DownloadString("https://github.com/${env:GIT_SCRIPT}/appveyor-git/raw/main/script/script.ps1"))

        iex ((New-Object System.Net.WebClient).DownloadString("${env:GIT_SCRIPT}/login/login.ps1"))
      }

      catch {
        throw "$_"
      }



      ##########################################



      swift -version
      cd asm2c
      swift build

      cd ../tools/asm
      convertAssemblyToC.sh
